### ISSUE TITLE
do you know what time it is ? 

### ISSUE THREAD

**Issue by empt1xo** [NotSoSuper/NotSoBot#68] opened 2018-08-31 13:13 UTC
UPDATE THE HECKING SOURCE TIME ;;;;!!!!

**Comment by ozzt** [comment] 2018-09-04 18:57
the source code was going to be uploaded tomorrow but you just delayed it by 2 years by asking
good job

**Comment by empt1xo** [comment] 2018-09-04 20:13
@ozzt excuse me what the fuck ?

**Comment by matmen** [comment] 2019-01-06 03:36
This is a duplicate of #11. Please use the search function to check if the issue you're reporting has already been reported.
Please close this @NotSoSuper

**Closed as completed** 2019-01-06 04:56 UTC

**Comment by empt1xo** [comment] 2019-01-07 21:20
@notsosuper update the source ?

**Comment by ozzt** [comment] 2020-01-22 20:17
the source code was going to be uploaded tomorrow but you just delayed it by 2 years by asking
good job

**Comment by matmen** [comment] 2020-01-22 20:28
the source code was going to be uploaded tomorrow but you just delayed it by 2 years by commenting on a dead issue
good job

**Comment by ozzt** [comment] 2020-01-22 20:29
@matmen

**Comment by matmen** [comment] 2020-01-22 20:33
@ozzt
